name: Rust

on:
  push:
    branches:
      - "main"
      - "renovate/**"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive

    - name: Install prerequisites
      run: sudo apt-get update &&
           sudo apt-get install -y --no-install-recommends
               protobuf-compiler cmake
 
    - name: Install stable Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    - uses: taiki-e/install-action@80a23c5ba9e1100fd8b777106e810018ed662a7b # v2.69.12
      with:
        tool: cargo-llvm-cov
    - uses: taiki-e/install-action@80a23c5ba9e1100fd8b777106e810018ed662a7b # v2.69.12
      with:
        tool: nextest
      
    - name: Rust Cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

    - name: Build
      run: cargo build --verbose

    - name: Run tests (with coverage)
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: lcov.info
        fail_ci_if_error: true
